# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TerminusDB Documentation
description: Documentation for TerminusDB
baseurl: "/docs/terminushub" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#theme: just-the-docs

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/horizontal_lockup_white.png"
logo: "https://terminusdb.com/img/logos/logo.svg"


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "TerminusDB Homepage":
    - "https://terminusdb.com"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 - TerminusDB |  Distributed by an <a href=\"https://github.com/terminusdb/terminusdb-server/blob/master/LICENSE\">Apache 2.0 license.</a>"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

sass:
  sass_dir: _sass
  style: compressed

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking:

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
